package com.asyncaiflow.service;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.asyncaiflow.planner.PlanDraftStep;
import com.asyncaiflow.planner.WorkflowPlanGenerator;
import com.asyncaiflow.support.ApiException;
import com.asyncaiflow.web.dto.CreateActionRequest;
import com.asyncaiflow.web.dto.CreateWorkflowRequest;
import com.asyncaiflow.web.dto.PlannerExecuteRequest;
import com.asyncaiflow.web.dto.PlannerExecuteResponse;
import com.asyncaiflow.web.dto.PlannerPlanRequest;
import com.asyncaiflow.web.dto.PlannerPlanResponse;
import com.asyncaiflow.web.dto.PlannerPlanStep;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;

@Service
public class PlannerService {

    private static final String PHASE1_ACTION_TYPE = "generate_patch";

    private final WorkflowPlanGenerator workflowPlanGenerator;
    private final WorkflowService workflowService;
    private final ActionService actionService;
    private final ObjectMapper objectMapper;

    @Autowired
    public PlannerService(WorkflowService workflowService, ActionService actionService, ObjectMapper objectMapper) {
        this.workflowPlanGenerator = new WorkflowPlanGenerator();
        this.workflowService = workflowService;
        this.actionService = actionService;
        this.objectMapper = objectMapper;
    }

    /** Package-private constructor used by unit tests that only invoke {@link #previewPlan}. */
    PlannerService() {
        this.workflowPlanGenerator = new WorkflowPlanGenerator();
        this.workflowService = null;
        this.actionService = null;
        this.objectMapper = new com.fasterxml.jackson.databind.ObjectMapper();
    }

    public PlannerPlanResponse previewPlan(PlannerPlanRequest request) {
        List<PlannerPlanStep> plan = workflowPlanGenerator
                .generatePlan(request.issue(), request.repoContext(), request.file())
                .stream()
                .map(this::toResponseStep)
                .toList();

        return new PlannerPlanResponse(plan);
    }

    @Transactional
    public PlannerExecuteResponse executePlan(PlannerExecuteRequest request) {
        // ── 路由决策：Drift 专案 DAG vs 标准 repair pipeline ─────────────────
        List<PlanDraftStep> steps;
        boolean isDriftPlan = request.difficulty() != null && request.difficulty() >= 3;

        if (isDriftPlan) {
            steps = workflowPlanGenerator.generateDriftPlan(
                    request.issue(),
                    request.difficulty(),
                    request.playerId() != null ? request.playerId() : "unknown");
        } else {
            steps = workflowPlanGenerator.generatePlan(
                    request.issue(),
                    request.repoContext() == null ? "" : request.repoContext(),
                    request.file() == null ? "" : request.file());
        }

        if (steps.isEmpty()) {
            throw new ApiException(HttpStatus.BAD_REQUEST, "Planner generated empty plan for the given issue");
        }

        var workflow = workflowService.createWorkflow(
                new CreateWorkflowRequest(truncateName(request.issue()), "Generated by planner"));
        Long workflowId = workflow.id();

        Map<Integer, Long> indexToActionId = new LinkedHashMap<>();
        List<Long> actionIds = new ArrayList<>();

        try {
            for (int i = 0; i < steps.size(); i++) {
                PlanDraftStep step = steps.get(i);

                List<Long> upstreamIds = step.dependsOn().stream()
                        .map(indexToActionId::get)
                        .filter(id -> id != null)
                        .toList();

                String payloadJson = serializePayload(step.payload());
                String actionType = resolveActionType(step.type());

                // Phase 5: inject drift_trigger before commit_changes
                // (skip for Drift plans — they already end with a drift_refresh step)
                if (!isDriftPlan && "commit_changes".equals(actionType) && !upstreamIds.isEmpty()) {
                    Long applyActionId = upstreamIds.get(upstreamIds.size() - 1);
                    var driftAction = actionService.createAction(new CreateActionRequest(
                            workflowId,
                            "drift_trigger",
                            "{\"schemaVersion\":\"v1\",\"event\":\"patch_applied\"}",
                            List.of(applyActionId),
                            1,
                            0,
                            60,
                            null));
                    actionIds.add(driftAction.id());
                    upstreamIds = List.of(driftAction.id());
                }

                var action = actionService.createAction(new CreateActionRequest(
                        workflowId,
                        actionType,
                        payloadJson,
                        upstreamIds.isEmpty() ? null : upstreamIds,
                        1,
                        10,
                        300,
                        null));

                indexToActionId.put(i, action.id());
                actionIds.add(action.id());
            }

            // Phase 4: auto-append commit_changes unless the planner already generated one
            // (skip for Drift plans — they already end with drift_refresh and don't need a git commit)
            String lastStepType = steps.get(steps.size() - 1).type();
            if (!isDriftPlan && (lastStepType == null || !lastStepType.toLowerCase().contains("commit"))) {
                Long lastActionId = actionIds.get(actionIds.size() - 1);
                String snippet = request.issue().length() > 50
                        ? request.issue().substring(0, 50)
                        : request.issue();
                String commitPayload = "{\"schemaVersion\":\"v1\",\"message\":\"Auto-commit: "
                        + snippet.replace("\"", "'") + "\",\"all\":true}";
                var commitAction = actionService.createAction(new CreateActionRequest(
                        workflowId,
                        "commit_changes",
                        commitPayload,
                        List.of(lastActionId),
                        1,
                        10,
                        300,
                        null));
                actionIds.add(commitAction.id());
            }
        } catch (ApiException e) {
            throw e;
        } catch (Exception e) {
            throw new ApiException(HttpStatus.INTERNAL_SERVER_ERROR,
                    "Failed to create actions for issue '" + truncateForLog(request.issue()) + "': " + e.getMessage());
        }

        return new PlannerExecuteResponse(workflowId, steps.size(), actionIds.size(), actionIds);
    }

    private String truncateForLog(String s) {
        if (s == null) return "";
        return s.length() > 80 ? s.substring(0, 80) + "…" : s;
    }

    private String truncateName(String s) {
        if (s == null) return "";
        return s.length() > 128 ? s.substring(0, 128) : s;
    }

    private String resolveActionType(String stepType) {
        if (stepType == null) {
            return PHASE1_ACTION_TYPE;
        }
        // Drift 专案 action 类型一律原样透传，不做任何映射
        if (stepType.startsWith("drift_")) {
            return stepType;
        }
        String normalized = stepType.toLowerCase();
        if (normalized.contains("search")) {
            return "search_code";
        }
        if (normalized.contains("read") || normalized.contains("load")) {
            return "read_file";
        }
        if (normalized.contains("plan")) {
            return "plan_workflow";
        }
        if (normalized.contains("commit")) {
            return "commit_changes";
        }
        if (normalized.contains("apply")) {
            return "apply_patch";
        }
        return PHASE1_ACTION_TYPE;
    }

    private String serializePayload(Map<String, Object> payload) {
        if (payload == null || payload.isEmpty()) {
            return null;
        }
        try {
            return objectMapper.writeValueAsString(payload);
        } catch (JsonProcessingException e) {
            return null;
        }
    }

    private PlannerPlanStep toResponseStep(PlanDraftStep step) {
        return new PlannerPlanStep(step.type(), step.payload(), step.dependsOn());
    }
}
